#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG="/usr/bin/bot"

start_service() {
    config_load bot
    local enabled
    config_get_bool enabled main enabled 0

    if [ "$enabled" -ne 1 ]; then
        return 0
    fi

    rm -f /tmp/bot.pid

    procd_open_instance
    procd_set_param command /bin/sh "$PROG"
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    pkill -9 -f "$PROG" 2>/dev/null
    rm -f /tmp/bot.pid
}

reload_service() {
    stop
    start
}
